"""empty message

Revision ID: 21c34cef5f94
Revises: 0fb83a678f21
Create Date: 2021-07-05 22:47:27.037251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c34cef5f94'
down_revision = '0fb83a678f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic', sa.Column('time_mean', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic', 'time_mean')
    # ### end Alembic commands ###
