"""empty message

Revision ID: 3e41fc8bcb04
Revises: f0fdaed44b57
Create Date: 2021-07-11 00:29:46.890438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e41fc8bcb04'
down_revision = 'f0fdaed44b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic', sa.Column('time_mean', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic', 'time_mean')
    # ### end Alembic commands ###
