"""empty message

Revision ID: 6d3d9399a4ef
Revises: 21c34cef5f94
Create Date: 2021-07-05 22:52:34.506346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3d9399a4ef'
down_revision = '21c34cef5f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic', sa.Column('linear', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic', 'linear')
    # ### end Alembic commands ###
