"""empty message

Revision ID: 71ef901851dc
Revises: 6d3d9399a4ef
Create Date: 2021-07-10 16:20:51.817719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ef901851dc'
down_revision = '6d3d9399a4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
