"""empty message

Revision ID: 8ded30ff5dd0
Revises: 
Create Date: 2021-06-20 21:55:28.999642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ded30ff5dd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=True, comment='ma cong ty'),
    sa.Column('company_name', sa.String(length=50), nullable=True, comment='ten cong ty'),
    sa.Column('description', sa.Text(), nullable=True, comment='mo ta'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_code'), 'company', ['company_code'], unique=True)
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_department_name'), 'department', ['department_name'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('staff_code', sa.String(length=255), nullable=False, comment='ma nhan vien'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='Ngày tháng năm sinh'),
    sa.Column('email_personal', sa.String(length=255), nullable=True, comment='email cá nhân'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='email nhân viên'),
    sa.Column('phone_number', sa.String(length=50), nullable=True, comment='Số điện thoại'),
    sa.Column('manager_id', sa.Integer(), nullable=True, comment='ID nguoi quan ly'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='ID cong ty'),
    sa.Column('date_onboard', sa.Date(), nullable=True, comment='Ngày vào công ty'),
    sa.Column('bank_name', sa.String(length=255), nullable=True, comment='tên ngân hàng'),
    sa.Column('branch_bank_name', sa.String(length=255), nullable=True, comment='chi nhánh ngân hàng'),
    sa.Column('account_number', sa.String(length=255), nullable=True, comment='Số tài khoản ngân hàng'),
    sa.Column('address_detail', sa.Text(), nullable=True, comment='địa chỉ chi tiết'),
    sa.Column('identity_card', sa.String(length=50), nullable=True, comment='Số CMND/CCCD/Hộ chiếu'),
    sa.Column('contract_type', sa.String(length=50), nullable=True, comment='Thoi vu|Chinh thuc...'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='avatar ca nhan'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_index(op.f('ix_staff_staff_code'), 'staff', ['staff_code'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('team_name', sa.String(length=255), nullable=True, comment='ten team'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_branch', sa.String(length=255), nullable=True, comment='ten chi nhanh'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_team_name'), 'team', ['team_name'], unique=False)
    op.create_table('company_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False, comment='email staff tương ứng từng cty'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_staff_email'), 'company_staff', ['email'], unique=True)
    op.create_table('role_title',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role_title_name', sa.String(length=255), nullable=True, comment='ten chuc danh'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_title_role_title_name'), 'role_title', ['role_title_name'], unique=False)
    op.create_table('staff_team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'team_id', name='_staff_team_unique')
    )
    op.create_table('department_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('role_title_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['role_title_id'], ['role_title.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'staff_id', name='_department_staff_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_staff')
    op.drop_table('staff_team')
    op.drop_index(op.f('ix_role_title_role_title_name'), table_name='role_title')
    op.drop_table('role_title')
    op.drop_index(op.f('ix_company_staff_email'), table_name='company_staff')
    op.drop_table('company_staff')
    op.drop_index(op.f('ix_team_team_name'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_staff_staff_code'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_department_department_name'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_company_code'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
