"""empty message

Revision ID: f0fdaed44b57
Revises: 71ef901851dc
Create Date: 2021-07-11 00:29:19.936583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fdaed44b57'
down_revision = '71ef901851dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
